// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HybridApp.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DataPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
//  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static DataPacket GetRootAsDataPacket(ByteBuffer _bb) { return GetRootAsDataPacket(_bb, new DataPacket()); }
  public static DataPacket GetRootAsDataPacket(ByteBuffer _bb, DataPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyDataPacket(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, DataPacketVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Title { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(4); }
  public double Data(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetDouble(__p.__vector(o) + j * 8) : (double)0; }
  public int DataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<double> GetDataBytes() { return __p.__vector_as_span<double>(6, 8); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public double[] GetDataArray() { return __p.__vector_as_array<double>(6); }

  public static Offset<HybridApp.FlatBuffers.DataPacket> CreateDataPacket(FlatBufferBuilder builder,
      StringOffset titleOffset = default(StringOffset),
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(2);
    DataPacket.AddData(builder, dataOffset);
    DataPacket.AddTitle(builder, titleOffset);
    return DataPacket.EndDataPacket(builder);
  }

  public static void StartDataPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(0, titleOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(1, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddDouble(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, double[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<double> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<double>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<HybridApp.FlatBuffers.DataPacket> EndDataPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<HybridApp.FlatBuffers.DataPacket>(o);
  }
  public static void FinishDataPacketBuffer(FlatBufferBuilder builder, Offset<HybridApp.FlatBuffers.DataPacket> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDataPacketBuffer(FlatBufferBuilder builder, Offset<HybridApp.FlatBuffers.DataPacket> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class DataPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Title*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Data*/, 8 /*double*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
